### PR TITLE
Update build-be.yml for Azure Pipelines

### PR DESCRIPTION
**Pull request by studert**

### CODE REVIEW

**Review by markusnoth — APPROVED** [review]
I guess you know what you're doing, but a bit more background info would be welcome :)

- why is master removed even though it still exists?
- why is develop not removed even though there is no such branch?
- and what is the purpose of the main branch here?

**Comment by studert** [comment]
Thank you for your inputs. These are some valid questions. Let me share some insight with you:

This change was initiated by @DaniRey with the background of the #BlackLivesMatter movement.
More details on how and why we want this change https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

As I did this change already for two other modules (SitecoreErrorManager and SitecoreUrlMapper v1), I also wanted to update our newest module (SitecoreUrlMapper v2).
See original ticket here: https://github.com/unic/SitecoreErrorManager/issues/20

The main goal of this PR is to change replace the _master_ trigger in the yml file as the _master_ branch will be replaced by the _main_ branch. _develop_ was already in that file and I did not want to remove this without talking to @schwindelig as the module owner. As soon as this change is merged and I was able to verify that the build is still green and working, the _master_ branch on this repo will be removed.

Do you think we should reconsider the _develop_ branch to be removed from the yml file?

**Comment by markusnoth** [comment]
Thanks @studert for the insights, in that case I'd just merge it as-is.
Not sure though what to think about the renaming itself, but that's another topic.
Anyway would probably make sense to communicate this to the whole team so everybody is informed that this is a new way to go and maybe also update the project repos accordingly. (and not having people spending hours in search for a master branch ;)

**Comment by studert** [comment]
Of course, I'll handle the internal communication.

**Pull request merged**
